### ISSUE TITLE
Ajax Collision with other Fields

### ISSUE THREAD

**Issue by bnomei** [texnixe/kirby-clone-field#1]
i had another field bases on the ajax field template. when adding your clone field they collided. suggestions
- change the the routes pattern to duplicate/(:any) https://github.com/texnixe/kirby-clone-field/blob/master/field/duplicate/duplicate.php#L114
- and in js as well https://github.com/texnixe/kirby-clone-field/blob/master/field/duplicate/assets/js/script.js#L41
- rename the js ajax function to something like 'duplicateAjax' in two places
  https://github.com/texnixe/kirby-clone-field/blob/master/field/duplicate/assets/js/script.js#L22 and https://github.com/texnixe/kirby-clone-field/blob/master/field/duplicate/assets/js/script.js#L37

will do the same with my field. ;-)

**Comment by texnixe** [comment]
I've fixed this in the develop branch.
