### ISSUE TITLE
Deep Copy Subpages

### ISSUE THREAD

**Issue by bnomei** [texnixe/kirby-clone-field#2]
Does not copy subpages. Which would be super awesome.

**Comment by texnixe** [comment]
Yes, in fact, I wanted to implement that feature as an option, but somehow I ran into an issue with the checkboxes and did not get round to finishing it ...

**Comment by bnomei** [comment]
i my case copy in with or without subpages depends on the template. so a field option in blueprint would suffice.

**Comment by texnixe** [comment]
A field option is quite a good idea, hadn't thought of that.

**Comment by bnomei** [comment]
not wanting to sound pushy... any idea when you will update the plugin? since if it takes more than 5 days from today, i will have to do it myself instead. ;-)

**Comment by jimhare** [comment]
For me I don't have this issue, the nested subpage structure is copied fine.

**Comment by bnomei** [comment]
@jimhare i can not verify that this is possible. tried clean kirby install. plugin code shows it get files and meta files only – no subpages (folders), right?

**Comment by jimhare** [comment]
Ah. It must be the `build:` command in my blueprint that created the nested pages. Sorry for the red herring!

**Comment by texnixe** [comment]
I just pushed a new version to the develop branch, if you would like to test it.

You can now use two options:

`copytree: true` will simply make a copy of the complete directory with all files and subfolders; default is false; 
`copyfile: true` will copy all images with their meta files of a single page; default is true.

The `copyfile` option is ignored if `copytree` is set to true.

Pls. let me know if you run into any issues.

**Comment by jimhare** [comment]
Great, I used `copytree: true` and it worked great. Thank you

**Comment by bnomei** [comment]
yes, copytree options works but it does not set the title of the new page to the entered value anymore.

**Comment by texnixe** [comment]
Yes, I know, I'm working on that.

**Comment by texnixe** [comment]
The title should now be set to the title entered in the input field. Not yet tested with multi-lang though.

**Comment by bnomei** [comment]
almost. missing a DS in line 171

```
$destPath = kirby()->roots->content() . DS . $this->page()->parent()->diruri() . DS . $slug;
```

**Comment by texnixe** [comment]
That's what I had first, but did not work. Does it work for you with the directory separator?

**Comment by bnomei** [comment]
yes. osx localhost mamp pro php 7 kirby 2.3.2.

**Comment by texnixe** [comment]
If I do that, I end up with two slashes and the if statement in line 173 does not work, mamp pro php 7 kirby 2.4 beta, have to test this with a fresh kirby 2.3.2 kit.

**Edit**: Ok, I've found the issue, it appears with page on the first level only, if there is not parent page.

**Comment by bnomei** [comment]
`diruri()` does not contain a trailing`/` as far as i can tell.

**Comment by texnixe** [comment]
Should be fixed now.
