### ISSUE TITLE
Automatically set Title of newly cloned page

### ISSUE THREAD

**Issue by jimhare** [texnixe/kirby-clone-field#4]
The field allows me to enter a title for the clone, in natural language including caps and spaces etc, but this doesn't get carried through to the new page. Instead it seems to only use what I enter in order to create a slug (folder) for the page. This is great, but it would be better if the field also set the new Title to the (pre-sluggified) string I wrote. I think users expect to see their title after redirection.

**Comment by texnixe** [comment]
I just added this to the development branch. The title should now be set to the title entered in the input field. Not yet tested with multi-lang though

**Comment by texnixe** [comment]
You mean when the whole tree is copied, right? Yeah, I haven't got round to it yet.
